import { lstatSync, readFileSync, realpathSync } from "node:fs";
import { spawn } from "node:child_process";
import { setTimeout as sleep } from "node:timers/promises";
import { basename, dirname, isAbsolute, join, relative, resolve, sep } from "node:path";
import { Value } from "typebox/value";
import { BACKGROUND_CONTEXT } from "@earendil-works/chord/context";
import { defineDoc, type Conversation } from "@earendil-works/pi-durable";
import type { Context } from "@earendil-works/chord";
import { AuthorizedRepository, WorkspaceIntent, type AuthorizedRepository as Authorization, type WorkspaceIntent as Intent, type WorkspaceLease, type WorkspaceReceipt, type WorkspaceScope, type WorkspaceSnapshot } from "./workspace-types.ts";

/* Before effects: preserve crash-after-effect, dirty/foreign/active work, lease
 * changes, source/provider drift, low disk, and shared-store ambiguity. */
const Receipts = defineDoc<{ receipts: Record<string, WorkspaceReceipt> }>({ kind: "projects.workspace-isolation", version: 1, scope: "conversation", history: "latest", fork: "initial", initial: () => ({ receipts: {} }) });
export type WorkspaceIsolation = { allocate(intent: Intent): Promise<WorkspaceReceipt>; reconcile(intent: Intent): Promise<WorkspaceReceipt>; release(intent: Intent): Promise<WorkspaceReceipt>; snapshot(): Promise<WorkspaceSnapshot> };
type Command = { code: number; stdout: string; stderr: string };
type Options = { conversation: Conversation; authority: { projectId: string; owner: string }; authorizedRepositories?: readonly Authorization[]; context?: Context; /** Test-only crash seam; production must not supply it. */ afterProviderEffect?: (receipt: WorkspaceReceipt) => Promise<void> | void; /** Test-only absolute missing executable; exercises actual OS probe failure only. */ testMissingProbeExecutable?: string; /** Test-only fixed PID-only lsof framing; exercises malformed-success preservation. */ testProbeWithoutCwdNames?: boolean };  
type Facts = { facts: Record<string, string>; reason: string | null };

/** A receipt-only module: host configuration, not a model, supplies authority. */
export function workspaceIsolation(options: Options): WorkspaceIsolation {
  const context = options.context ?? BACKGROUND_CONTEXT; const allowed = options.authorizedRepositories ?? []; const authority = options.authority; if (options.testMissingProbeExecutable !== undefined) { if (!isAbsolute(options.testMissingProbeExecutable)) throw new Error("Test missing probe executable must be absolute"); if (lstatSync(options.testMissingProbeExecutable, { throwIfNoEntry: false })) throw new Error("Test missing probe executable must not exist"); }
  async function get(id: string) { return options.conversation.commit(async tx => { const x = await tx.doc(Receipts, options.conversation.id); return x.receipts[id] ? dto(x.receipts[id]) : undefined; }, context); }
  async function put(value: WorkspaceReceipt) { const out = dto(value); await options.conversation.commit(async tx => { (await tx.doc(Receipts, options.conversation.id)).receipts[out.intentId] = out; }, context); return out; }
  async function allocate(intent: Intent) {
    authorize(intent, allowed, authority); const old = await get(intent.id); if (old) { if (!sameFrozenIntent(old, intent)) throw new Error("Existing workspace receipt intent/scope differs; refusing adoption"); return old; }
    await put(receipt(intent, "prepared", {}, null, null, null)); // Durable intent precedes unsafe CLI.
    const pre = await preflight(intent.scope, false); if (pre.reason) return put(receipt(intent, "blocked", pre.facts, null, null, pre.reason));
    const effect = intent.scope.provider === "git" ? await addGit(intent, pre.facts) : await addArc(intent, pre.facts);
    if (effect.state === "allocated") await options.afterProviderEffect?.(dto(effect));
    return put(effect);
  }
  async function reconcile(intent: Intent) {
    authorize(intent, allowed, authority); const old = await get(intent.id); if (!old) return receipt(intent, "blocked", {}, null, null, "No prepared Durable intent exists"); if (!sameFrozenIntent(old, intent)) throw new Error("Existing workspace receipt intent/scope differs; refusing reconciliation");
    if (["blocked", "released"].includes(old.state)) return old;
    const pre = await preflight(intent.scope, true); if (pre.reason) return put(receipt(intent, old.state === "prepared" ? "blocked" : "preserved", pre.facts, old.workspacePath, old.lease, pre.reason));
    const actual = intent.scope.provider === "git" ? await gitEntry(intent.scope) : await arcEntry(intent.scope);
    if (!actual || !exact(intent.scope, actual)) return put(receipt(intent, "uncertain", { ...pre.facts, ...(actual?.facts ?? {}) }, old.workspacePath, actual?.lease ?? old.lease, "Observed provider state is absent, ambiguous, or differs from the frozen intent; refusing recreation"));
    return put(receipt(intent, "allocated", { ...pre.facts, ...actual.facts }, intent.scope.workspacePath, actual.lease, null));
  }
  async function release(intent: Intent) {
    authorize(intent, allowed, authority); const old = await get(intent.id); if (!old || !["allocated", "preserved"].includes(old.state)) return receipt(intent, "blocked", {}, null, null, "Only an allocated or freshly rechecked preserved receipt can be released");
    const current = await reconcile(intent); if (current.state !== "allocated") return current;
    const probe = await active(intent.scope.workspacePath, options.testMissingProbeExecutable, options.testProbeWithoutCwdNames); if (probe) return put(receipt(intent, "preserved", current.providerFacts, current.workspacePath, current.lease, typeof probe === "string" ? `Workspace activity probe failed: ${probe}` : "An active process has this workspace as cwd"));
    const status = await command(intent.scope.provider === "git" ? "/usr/bin/git" : "/opt/homebrew/bin/arc", intent.scope.provider === "git" ? ["status", "--porcelain=v1", "--untracked-files=all"] : ["status", "--short"], intent.scope.workspacePath);
    if (status.code || status.stdout.trim()) return put(receipt(intent, "preserved", current.providerFacts, current.workspacePath, current.lease, "Workspace is dirty or status cannot be verified"));
    if (intent.scope.provider === "git") {
      const lock = await command("/usr/bin/git", ["worktree", "list", "--porcelain"], intent.scope.ownerCheckout); const entry = parseGit(lock.stdout, intent.scope.workspacePath);
      if (!entry || entry.locked !== `workspace-intent:${intent.id}`) return put(receipt(intent, "preserved", current.providerFacts, current.workspacePath, null, "Git lock is absent or not owned by this exact intent"));
      const unlock = await command("/usr/bin/git", ["worktree", "unlock", intent.scope.workspacePath], intent.scope.ownerCheckout); if (unlock.code) return put(receipt(intent, "preserved", current.providerFacts, current.workspacePath, null, "Owned Git worktree could not be unlocked"));
      const remove = await command("/usr/bin/git", ["worktree", "remove", intent.scope.workspacePath], intent.scope.ownerCheckout); if (remove.code) return put(receipt(intent, "preserved", { ...current.providerFacts, remove: short(remove.stderr) }, current.workspacePath, null, "Unforced Git removal failed after unlock; preserving work"));
      return put(receipt(intent, "released", { ...current.providerFacts, remove: "unlocked-unforced" }, null, null, null));
    }
    const renewed = await command("/usr/local/bin/arc-wt", ["lease", "renew", intent.scope.workspaceName, "--owner", intent.scope.owner]); if (renewed.code) return put(receipt(intent, "preserved", current.providerFacts, current.workspacePath, current.lease, "Arc lease renewal failed"));
    const entry = await arcEntry(intent.scope); if (!entry || !entry.lease || !exact(intent.scope, entry)) return put(receipt(intent, "preserved", current.providerFacts, current.workspacePath, current.lease, "Arc renewed lease facts changed or cannot be verified"));
    const remove = await command("/usr/local/bin/arc-wt", ["remove", intent.scope.workspaceName, "--lease-owner", intent.scope.owner, "--lease-renewed", entry.lease.renewedAt]);
    return remove.code ? put(receipt(intent, "preserved", { ...entry.facts, remove: short(remove.stderr) }, current.workspacePath, entry.lease, "Fenced Arc removal failed; preserving work")) : put(receipt(intent, "released", { ...entry.facts, remove: "fenced-clean" }, null, null, null));
  }
  async function snapshot(): Promise<WorkspaceSnapshot> { return options.conversation.commit(async tx => ({ receipts: Object.values((await tx.doc(Receipts, options.conversation.id)).receipts).map(dto) }), context); }
  return { allocate, reconcile, release, snapshot };
}

function sameFrozenIntent(receipt: WorkspaceReceipt, intent: Intent): boolean { return receipt.intentId === intent.id && receipt.attemptId === intent.attemptId && JSON.stringify(receipt.scope) === JSON.stringify(intent.scope); }
function authorize(intent: Intent, allowed: readonly Authorization[], authority: { projectId: string; owner: string }) {
  if (!Value.Check(WorkspaceIntent, intent)) throw new Error("Invalid workspace intent");
  if (intent.scope.projectId !== authority.projectId || intent.scope.owner !== authority.owner) throw new Error("Workspace project or lease owner does not match host authority");
  const match = allowed.find(a => Value.Check(AuthorizedRepository, a) && a.repositoryId === intent.scope.repositoryId && a.provider === intent.scope.provider && a.approvedRoot === intent.scope.approvedRoot && a.ownerCheckout === intent.scope.ownerCheckout);
  if (!match) throw new Error("Workspace repository/scope is not authorized by host configuration");
  for (const file of intent.scope.fileOwnership) if (isAbsolute(file) || file.split(/[\\/]/).includes("..") || !(file === match.fileOwnershipPrefix || file.startsWith(`${match.fileOwnershipPrefix}/`))) throw new Error("File ownership is outside the host-approved prefix");
}
async function preflight(s: WorkspaceScope, exists: boolean): Promise<Facts> {
  try { const owner = dir(s.ownerCheckout), root = dir(s.approvedRoot), target = resolve(realpathSync(dirname(s.workspacePath)), basename(s.workspacePath)); if (!inside(root, target) || owner === target) return { facts: {}, reason: "Workspace path escapes its approved allocation root" }; if (Boolean(lstatSync(target, { throwIfNoEntry: false })) !== exists) return { facts: { ownerCheckout: owner, workspacePath: target }, reason: exists ? "Expected workspace path is absent" : "Workspace target already exists" };
    if (s.provider === "git") { const head = await command("/usr/bin/git", ["rev-parse", "HEAD"], owner), clean = await command("/usr/bin/git", ["status", "--porcelain=v1", "--untracked-files=all"], owner); if (head.code || clean.code || (!exists && clean.stdout.trim() && !s.allowDirtyOwner)) return { facts: {}, reason: "Git owner is unreadable or dirty" }; return { facts: { ownerCheckout: owner, ownerHead: head.stdout.trim(), workspacePath: target }, reason: !exists && head.stdout.trim() !== s.headRevision ? "Git owner head drifted" : null }; }
    const cfg = await command("/usr/local/bin/arc-wt", ["config"]); const rootCheck = await command("/opt/homebrew/bin/arc", ["root"], owner); const info = await command("/opt/homebrew/bin/arc", ["info", "--json"], owner); const disk = await command("/bin/df", ["-kP", process.env.HOME ?? "/"]); if (cfg.code || rootCheck.code || info.code || disk.code) return { facts: {}, reason: "Arc config/source/identity/disk preflight failed" }; const config = configFacts(cfg.stdout); const identity = JSON.parse(info.stdout) as { repository?: string; hash?: string }; const available = Number(disk.stdout.trim().split("\n").at(-1)?.trim().split(/\s+/)[3]); const facts = { ownerCheckout: owner, workspacePath: target, repo: identity.repository ?? "", ownerHead: identity.hash ?? "", objectStore: config.object_store_path ?? "", freeKiB: String(available) }; if (identity.repository !== s.repositoryId || resolve(rootCheck.stdout.trim()) !== owner || config.object_store_path !== s.sharedObjectStore || available < 10 * 1024 * 1024) return { facts, reason: "Arc source identity, shared object store, or physical free space differs from frozen scope" }; return { facts, reason: null };
  } catch (e) { return { facts: {}, reason: e instanceof Error ? e.message : String(e) }; }
}
async function addGit(i: Intent, facts: Record<string,string>) { const x = await command("/usr/bin/git", ["worktree", "add", "--lock", "--reason", `workspace-intent:${i.id}`, "-b", i.scope.branch, i.scope.workspacePath, i.scope.baseRevision], i.scope.ownerCheckout); if (x.code) return receipt(i,"blocked",{...facts,add:short(x.stderr)},null,null,"Git add failed"); const found=await gitEntry(i.scope); return found&&exact(i.scope,found)?receipt(i,"allocated",{...facts,...found.facts},i.scope.workspacePath,null,null):receipt(i,"uncertain",facts,i.scope.workspacePath,null,"Git effect lacks exact receipt facts"); }
async function addArc(i: Intent, facts: Record<string,string>) { const x=await command("/usr/local/bin/arc-wt",["add",i.scope.branch,"--name",i.scope.workspaceName,"--path",i.scope.workspacePath,"--base",i.scope.baseRevision,"--repo",i.scope.repositoryId,"--object-store-path",i.scope.sharedObjectStore!,"--lease-owner",i.scope.owner,"--lease-reason",i.scope.leaseReason]); if(x.code)return receipt(i,"blocked",{...facts,add:short(x.stderr)},null,null,"Arc add failed"); const observed=await arcEntryAfterAdd(i.scope); const found=observed.entry; return found&&exact(i.scope,found)?receipt(i,"allocated",{...facts,...observed.facts,...found.facts},i.scope.workspacePath,found.lease,null):receipt(i,"uncertain",{...facts,...observed.facts,...(found?.facts??{})},i.scope.workspacePath,found?.lease??null,"Arc effect lacks exact leased receipt facts"); }
async function gitEntry(s: WorkspaceScope) { const x=await command("/usr/bin/git",["worktree","list","--porcelain"],s.ownerCheckout); const e=parseGit(x.stdout,s.workspacePath); return e?{facts:{path:e.worktree,head:e.HEAD,branch:e.branch,locked:e.locked??""},lease:null}:null; }
async function arcEntry(s: WorkspaceScope) { return (await observeArcEntry(s)).entry; }
async function observeArcEntry(s: WorkspaceScope): Promise<{ entry: { facts: Record<string,string>; lease: WorkspaceLease|null } | null; observation: string }> { const x=await command("/usr/local/bin/arc-wt",["list",s.workspaceName,"--porcelain","--verbose"]); if(x.code)return {entry:null,observation:`command:${x.code}:${short(x.stderr)}`}; const e=parseArc(x.stdout); if(!e)return {entry:null,observation:"incomplete-porcelain"}; if(!e.store || !s.sharedObjectStore)return {entry:null,observation:"missing-store"}; const effective = arcEffectiveStore(e.store, s.repositoryId); if(effective===null)return {entry:null,observation:"invalid-local-metadata"}; const lease=e["lease-owner"]&&e["lease-renewed"]?{name:e.name,owner:e["lease-owner"],renewedAt:e["lease-renewed"]}:null; return {entry:{facts:{path:e.worktree??"",head:e.HEAD??"",branch:e.branch??"",repo:e.repo??"",store:e.store,base:e.base??"",objectStore:effective},lease},observation:"complete"}; }
async function arcEntryAfterAdd(s: WorkspaceScope): Promise<{ entry: { facts: Record<string,string>; lease: WorkspaceLease|null } | null; facts: Record<string,string> }> { const facts: Record<string,string>={}; for(let attempt=0;attempt<5;attempt++){ const observed=await observeArcEntry(s); facts[`arcObservation${attempt}`]=observed.observation; if(observed.entry)return {entry:observed.entry,facts}; if(observed.observation!=="incomplete-porcelain" || attempt===4)return {entry:null,facts}; await sleep(1000); } return {entry:null,facts}; }
function arcEffectiveStore(localStore:string, repository:string):string|null { try { const file=join(realpathSync(localStore),".arc","config"), text=readFileSync(file,"utf8"); if(text.length>32_768)return null; const repo=/^Repository:\s*"([^"]+)"\s*$/m.exec(text)?.[1], store=/^ObjectStorePath:\s*"([^"]+)"\s*$/m.exec(text)?.[1]; if(repo!==repository || !store)return null; return realpathSync(store); } catch { return null; } }
function storeIdentity(path:string):{ resolved:string; dev:string; ino:string }|null { try { if(!isAbsolute(path))return null; const lexical=lstatSync(path,{bigint:true}); if(lexical.isSymbolicLink()||!lexical.isDirectory())return null; const resolved=realpathSync(path), actual=lstatSync(resolved,{bigint:true}); return actual.isSymbolicLink()||!actual.isDirectory()?null:{resolved,dev:actual.dev.toString(),ino:actual.ino.toString()}; } catch { return null; } }
function sameStore(expected:string, observed:string):boolean { const left=storeIdentity(expected),right=storeIdentity(observed); return left!==null&&right!==null&&left.dev===right.dev&&left.ino===right.ino; }
function exact(s:WorkspaceScope, a:{facts:Record<string,string>;lease:WorkspaceLease|null}) { return a.facts.path===resolve(s.workspacePath)&&a.facts.head===s.baseRevision&&(s.provider === "git" ? a.facts.branch === `refs/heads/${s.branch}` : a.facts.branch===s.branch&&a.facts.repo===s.repositoryId&&a.facts.base===s.baseRevision&&sameStore(s.sharedObjectStore!,a.facts.objectStore)&&a.lease?.name===s.workspaceName&&a.lease.owner===s.owner); }
function parseGit(text:string,path:string) { return text.trim().split("\n\n").map(b=>Object.fromEntries(b.split("\n").map(l=>{const [k,...v]=l.split(" ");return[k,v.join(" ")]}))).find(x=>x.worktree===resolve(path)); }
function parseArc(text:string) { const rows=text.trim().split("\n\n").filter(Boolean); if(rows.length!==1)return null; const out:Record<string,string>={}; for(const line of rows[0].split("\n")){const at=line.indexOf(" ");if(at<1)return null;const k=line.slice(0,at),v=line.slice(at+1);if(out[k]!==undefined&&out[k]!==v)return null;out[k]=v;} return out.name&&out.worktree&&out.branch&&out.HEAD?out:null; }
function configFacts(t:string){return Object.fromEntries(t.split("\n").flatMap(l=>{const m=/^([a-z_]+):\s*(.+)$/.exec(l);return m?[[m[1],resolve(m[2].replace(/^~/,process.env.HOME??""))]]:[]}));}
async function active(path:string, missingProbeExecutable?:string, pidOnly?:boolean):Promise<boolean|string>{const x=await command(missingProbeExecutable??"/usr/sbin/lsof",["-a","-d","cwd",pidOnly?"-Fp":"-Fn"]); if (x.code === 1 && x.stderr === "" && x.stdout === "") return false; if (x.code !== 0) return `exit ${x.code}: ${short(x.stderr)}`; if (x.stderr !== "") return `stderr: ${short(x.stderr)}`; const lines=x.stdout.split("\n"); if (x.stdout === "") return "empty successful cwd probe"; let pid=false,cwd=false,names=0,matched=false; const target=resolve(path); for(const line of lines){if(line==="")continue; if(/^p\d+$/.test(line)){if(pid&&(!cwd||names!==1))return "malformed or incomplete cwd probe records";pid=true;cwd=false;names=0;continue;} if(line==="fcwd"&&pid&&!cwd){cwd=true;continue;} if(line.startsWith("n")&&pid&&cwd){const name=line.slice(1);if(!isAbsolute(name)||++names!==1)return "malformed or incomplete cwd probe records";if(inside(target,resolve(name)))matched=true;continue;} return "malformed or incomplete cwd probe records";} if(!pid||!cwd||names!==1)return "malformed or incomplete cwd probe records"; return matched;}
function receipt(i:Intent,state:WorkspaceReceipt["state"],facts:Record<string,string>,path:string|null,lease:WorkspaceLease|null,reason:string|null):WorkspaceReceipt{return {intentId:i.id,attemptId:i.attemptId,state,scope:dto(i.scope),providerFacts:dto(facts),workspacePath:path,lease:lease?dto(lease):null,reason};} function dto<T>(v:T):T{return JSON.parse(JSON.stringify(v)) as T;} function dir(p:string){if(!isAbsolute(p)||lstatSync(p).isSymbolicLink())throw Error("Path must be absolute and not a symlink");return realpathSync(p);}function inside(a:string,b:string){const x=relative(a,b);return x===""||(!x.startsWith(`..${sep}`)&&x!==".."&&!isAbsolute(x));}function short(x:string){return x.trim().slice(-1000);}function command(file:string,args:string[],cwd?:string):Promise<Command>{return new Promise(done=>{const c=spawn(file,args,{cwd,shell:false,env:{PATH:"/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin"},stdio:["ignore","pipe","pipe"]});let o="",e="";c.stdout.on("data",x=>o+=x);c.stderr.on("data",x=>e+=x);c.on("error",x=>done({code:-1,stdout:o,stderr:String(x)}));c.on("close",x=>done({code:x??-1,stdout:o,stderr:e}));});}
